version: "3"

services:
  test_function:
    image: denvazh/gatling
    environment:
      BASEURL: http://host.docker.internal:8081/
      ENDPOINT: hello?name=ducas
      USERS: 100
      JAVA_OPTS: -Dduration=300
      HOST_HEADER: myfn.foo
    volumes:
      - ./conf:/opt/gatling/conf
      - ./user-files:/opt/gatling/user-files
      - ./results:/opt/gatling/results

